name = "peermessenger-signal"
main = "server/cloudflare-worker.js"
compatibility_date = "2024-05-01"

[[durable_objects.bindings]]
name = "ROOMS"
class_name = "Room"

[[migrations]]
tag = "v1"
new_classes = ["Room"]
